### ISSUE TITLE
Show example USPSConfig.json file or note how to create one in README

### ISSUE THREAD

**Issue by joemasilotti** [ConceptsInCode/PackageTracker#8]
I want to send a minor PR and comment on one of your tests. So I cloned the repo and wasn't able to build because I don't have the USPS.json file. I know from the podcast that this is where you are storing credentials for the service, but if I were a new user to the repo I would not.

Can you please add an example USPS.json file with bogus credentials? Perhaps, `/* your credentials here */`, and/or note in the README how one can generate this file?

**Comment by SixFiveSoftware** [comment]
Good idea Joe! I'll be able to add that here shortly when I get back to my computer. Thank you.

**Comment by SixFiveSoftware** [comment]
@joemasilotti I just added the key into the app, with a disclosure in the README. If people want to use the app or things from it, they can get their own key. That way, people can still build the code and run. Please let me know if this works for you.

**Comment by joemasilotti** [comment]
Works great, thanks for the quick update! Now to just figure out this failing test...
